-- MySQL Script generated by MySQL Workbench
-- Sun May 16 02:51:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ciclology
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ciclology
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciclology` DEFAULT CHARACTER SET utf8 ;
USE `ciclology` ;

-- -----------------------------------------------------
-- Table `ciclology`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `Cedula` BIGINT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefono` BIGINT NOT NULL,
  `password` TEXT(50) NULL,
  `fechaCaptura` DATE NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `apellido` VARCHAR(200) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `telefono` BIGINT NOT NULL,
  `cedula` BIGINT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `IdCompras_UNIQUE` (`id_cliente` ASC),
  INDEX `fk_clientes_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_clientes_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ciclology`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`categorias` (
  `id_categoria` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `nombreCategoria` VARCHAR(150) NOT NULL,
  `fechaCaptura` DATE NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `fk_categorias_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_categorias_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ciclology`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Marca` (
  `id_marca` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `nombreMarca` VARCHAR(150) NOT NULL,
  `fechaCaptura` DATE NULL,
  PRIMARY KEY (`id_marca`),
  INDEX `fk_Marca_Usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_Marca_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ciclology`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`imagenes` (
  `id_imagen` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `nombre` VARCHAR(500) NOT NULL,
  `ruta` VARCHAR(500) NOT NULL,
  `fechaSubida` DATE NULL,
  PRIMARY KEY (`id_imagen`),
  INDEX `fk_Foto_categorias1_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_Foto_categorias1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `ciclology`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Color` (
  `id_color` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `nombreColor` VARCHAR(150) NOT NULL,
  `fechaCaptura` DATE NULL,
  PRIMARY KEY (`id_color`),
  INDEX `fk_Color_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_Color_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ciclology`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`articulos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_marca` INT NOT NULL,
  `descripcion` TEXT NULL,
  `precio` BIGINT NOT NULL,
  `cantidad` BIGINT NOT NULL,
  `fechaCaptura` DATE NULL,
  `id_imagen` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_color` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `idProducto_UNIQUE` (`id_producto` ASC),
  INDEX `fk_Producto_Categoria1_idx` (`id_categoria` ASC),
  INDEX `fk_Producto_Marca1_idx` (`id_marca` ASC),
  INDEX `fk_articulos_imagenes1_idx` (`id_imagen` ASC),
  INDEX `fk_articulos_usuarios1_idx` (`id_usuario` ASC),
  INDEX `fk_articulos_Color1_idx` (`id_color` ASC),
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `ciclology`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Marca1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `ciclology`.`Marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_imagenes1`
    FOREIGN KEY (`id_imagen`)
    REFERENCES `ciclology`.`imagenes` (`id_imagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ciclology`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_Color1`
    FOREIGN KEY (`id_color`)
    REFERENCES `ciclology`.`Color` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`ventas` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `precio` BIGINT NOT NULL,
  `fechaCompra` DATE NOT NULL,
  PRIMARY KEY (`id_venta`),
  UNIQUE INDEX `idfactura_UNIQUE` (`id_venta` ASC),
  INDEX `fk_ventas_articulos1_idx` (`id_producto` ASC),
  INDEX `fk_ventas_usuarios1_idx` (`id_usuario` ASC),
  INDEX `fk_ventas_clientes1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_ventas_articulos1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `ciclology`.`articulos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ciclology`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ciclology`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
