-- MySQL Script generated by MySQL Workbench
-- Mon May 10 11:01:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ciclology
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ciclology
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciclology` DEFAULT CHARACTER SET utf8 ;
USE `ciclology` ;

-- -----------------------------------------------------
-- Table `ciclology`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `Cedula` BIGINT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefono` BIGINT NOT NULL,
  `password` TEXT(50) NULL,
  `fechaCaptura` DATE NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Compras` (
  `IdCompras` INT NOT NULL AUTO_INCREMENT,
  `FechaDeCompras` DATE NOT NULL,
  `NumeroDeFactura` BIGINT NOT NULL,
  `ValorTotal` BIGINT NOT NULL,
  `Proveedor_Id` INT NOT NULL,
  PRIMARY KEY (`IdCompras`),
  UNIQUE INDEX `IdCompras_UNIQUE` (`IdCompras` ASC),
  INDEX `fk_Compras_Usuario_idx` (`Proveedor_Id` ASC),
  CONSTRAINT `fk_Compras_Usuario`
    FOREIGN KEY (`Proveedor_Id`)
    REFERENCES `ciclology`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Marca` (
  `idMarca` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Proveedor_Id` INT NOT NULL,
  PRIMARY KEY (`idMarca`),
  INDEX `fk_Marca_Usuario1_idx` (`Proveedor_Id` ASC),
  CONSTRAINT `fk_Marca_Usuario1`
    FOREIGN KEY (`Proveedor_Id`)
    REFERENCES `ciclology`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Producto` (
  `IdProducto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Categoria_id` INT NOT NULL,
  `Marca_id` INT NOT NULL,
  `Talla` SET('S', 'M', 'L', 'XL', 'XXL') NULL,
  `IVA` VARCHAR(45) NOT NULL,
  `Precio_Base` DOUBLE NOT NULL,
  `Estado` ENUM('Disponibilidad', 'Nodisponible') NOT NULL,
  PRIMARY KEY (`IdProducto`),
  UNIQUE INDEX `idProducto_UNIQUE` (`IdProducto` ASC),
  INDEX `fk_Producto_Categoria1_idx` (`Categoria_id` ASC),
  INDEX `fk_Producto_Marca1_idx` (`Marca_id` ASC),
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `ciclology`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Marca1`
    FOREIGN KEY (`Marca_id`)
    REFERENCES `ciclology`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Cotizacion` (
  `idCotizacion` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Cliente_Id` INT NOT NULL,
  `Codigo` VARCHAR(45) NOT NULL,
  `ValidoDias` BIGINT NOT NULL,
  `ValorTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`idCotizacion`),
  UNIQUE INDEX `idDetalle-venta_UNIQUE` (`idCotizacion` ASC),
  INDEX `fk_Cotizacion_Usuario1_idx` (`Cliente_Id` ASC),
  CONSTRAINT `fk_Cotizacion_Usuario1`
    FOREIGN KEY (`Cliente_Id`)
    REFERENCES `ciclology`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Venta` (
  `IdVenta` INT NOT NULL AUTO_INCREMENT,
  `NumerodeFactura` TINYINT(200) NOT NULL,
  `FechadeFactura` DATE NOT NULL,
  `ValorDeFactura` BIGINT NOT NULL,
  `Estado` ENUM('En Proceso', 'En Camino', 'Entregado') NOT NULL,
  `TipoDeVenta` ENUM('Directa', 'Accesoria', 'Telefonica', 'TiendaOnline', 'Apartado') NOT NULL,
  `Cotizacion_Id` INT NULL,
  `Cliente_Id` INT NOT NULL,
  PRIMARY KEY (`IdVenta`),
  UNIQUE INDEX `idfactura_UNIQUE` (`IdVenta` ASC),
  INDEX `fk_factura_Accesoria1_idx` (`Cotizacion_Id` ASC),
  INDEX `fk_Venta_Usuario1_idx` (`Cliente_Id` ASC),
  CONSTRAINT `fk_factura_Accesoria1`
    FOREIGN KEY (`Cotizacion_Id`)
    REFERENCES `ciclology`.`Cotizacion` (`idCotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Usuario1`
    FOREIGN KEY (`Cliente_Id`)
    REFERENCES `ciclology`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Color` (
  `idColor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Stock` BIGINT NOT NULL,
  `Producto_IdProducto` INT NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idColor`),
  INDEX `fk_Color_Producto1_idx` (`Producto_IdProducto` ASC),
  CONSTRAINT `fk_Color_Producto1`
    FOREIGN KEY (`Producto_IdProducto`)
    REFERENCES `ciclology`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Detalle_Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Detalle_Ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `Factura_Id` INT NOT NULL,
  `Color_Id` INT NOT NULL,
  `Cantidad` BIGINT NOT NULL,
  `PrecioVenta` BIGINT NOT NULL,
  `Talla` CHAR(3) NULL,
  PRIMARY KEY (`idVentas`),
  UNIQUE INDEX `idVentas_UNIQUE` (`idVentas` ASC),
  INDEX `fk_Ventas_factura1_idx` (`Factura_Id` ASC),
  INDEX `fk_Detalle-Ventas_Color1_idx` (`Color_Id` ASC),
  CONSTRAINT `fk_Ventas_factura1`
    FOREIGN KEY (`Factura_Id`)
    REFERENCES `ciclology`.`Venta` (`IdVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle-Ventas_Color1`
    FOREIGN KEY (`Color_Id`)
    REFERENCES `ciclology`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Foto` (
  `idFoto` INT NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `ruta` VARCHAR(90) NOT NULL,
  `Color_idColor` INT NOT NULL,
  PRIMARY KEY (`idFoto`),
  INDEX `fk_Foto_Color1_idx` (`Color_idColor` ASC),
  CONSTRAINT `fk_Foto_Color1`
    FOREIGN KEY (`Color_idColor`)
    REFERENCES `ciclology`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`Cotizacion_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`Cotizacion_Productos` (
  `idCotizacion_Producto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cotizacion_id` INT NOT NULL,
  `Color_idColor` INT NOT NULL,
  `Cantidad` BIGINT NOT NULL,
  `Precio_Venta` BIGINT NOT NULL,
  `Talla` CHAR(3) NULL,
  PRIMARY KEY (`idCotizacion_Producto`),
  INDEX `fk_Cotizacion_Productos_Cotizacion1_idx` (`Cotizacion_id` ASC),
  INDEX `fk_Cotizacion_Productos_Color1_idx` (`Color_idColor` ASC),
  CONSTRAINT `fk_Cotizacion_Productos_Cotizacion1`
    FOREIGN KEY (`Cotizacion_id`)
    REFERENCES `ciclology`.`Cotizacion` (`idCotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cotizacion_Productos_Color1`
    FOREIGN KEY (`Color_idColor`)
    REFERENCES `ciclology`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclology`.`DetalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclology`.`DetalleCompra` (
  `idDetalleCompra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Compras_Id` INT NOT NULL,
  `Color_id` INT NOT NULL,
  `Cantidad` BIGINT NOT NULL,
  `Precio` BIGINT NOT NULL,
  PRIMARY KEY (`idDetalleCompra`),
  INDEX `fk_DetalleCompra_Compras1_idx` (`Compras_Id` ASC),
  INDEX `fk_DetalleCompra_Color1_idx` (`Color_id` ASC),
  CONSTRAINT `fk_DetalleCompra_Compras1`
    FOREIGN KEY (`Compras_Id`)
    REFERENCES `ciclology`.`Compras` (`IdCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleCompra_Color1`
    FOREIGN KEY (`Color_id`)
    REFERENCES `ciclology`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
